$(document).ready(function(){
    $('.iconOne').click(function(){
        $('.hidden').toggle();
        $('.iconOne').toggle();
    });
    $('.hidden').click(function(){
        $('.iconOne').toggle();
        $('.hidden').toggle();
    });
});